app = "errmon-items-api"
primary_region = "gru"
kill_signal = "SIGTERM"
kill_timeout = 45
console_command = "bin/rails console"

[build]
dockerfile = "Dockerfile"

[deploy]
release_command = "bin/rails db:migrate"
strategy = "rolling"

[env]
RAILS_HOST = "errmon-items-api.fly.dev"
RAILS_TLD_LENGTH = "2"
RAILS_ASSUME_SSL = "false"
RAILS_PUMA_WORKERS = "2"
RAILS_MAX_THREADS = "5"
DATABASE_STATEMENT_TIMEOUT = "10s"
RACK_TIMEOUT_SERVICE_PAST_WAIT = "false"
RACK_TIMEOUT_SERVICE_TIMEOUT = "10"
RACK_TIMEOUT_TERM_ON_TIMEOUT = "1"
RACK_TIMEOUT_WAIT_OVERTIME = "false"
RACK_TIMEOUT_WAIT_TIMEOUT = "false"

[processes]
web = ""
worker = "bin/rake sneakers:run"

[http_service]
processes = ["web"]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1

[[http_service.checks]]
grace_period = "5s"
interval = "10s"
timeout = "5s"
protocol = "http"
method = "GET"
path = "/up"

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1

[[statics]]
guest_path = "/app/public"
url_prefix = "/"
