development:
  adapter: redis
  url: <%= Rails.application.config.action_cable_redis_url %>
  channel_prefix: errmon_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.application.config.action_cable_redis_url %>
  channel_prefix: errmon_production
