default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Rails.application.config.database_pool_size %>
  connect_timeout: <%= Rails.application.config.database_connect_timeout %>
  checkout_timeout: <%= Rails.application.config.database_checkout_timeout %>
  variables:
    statement_timeout: <%= Rails.application.config.database_statement_timeout %>
  host: <%= ENV.fetch('DATABASE_HOST', 'postgres') %>
  port: <%= ENV.fetch('DATABASE_PORT', '5432') %>
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>

development:
  <<: *default
  database: errmon_items_api_development

test:
  <<: *default
  database: errmon_items_api_test

production:
  <<: *default
  database: errmon_items_api_production
