name: continuous-integration

on:
  pull_request:
  push:
    branches:
      - main

env:
  DATABASE_HOST: localhost
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres
  RACK_ENV: test
  RAILS_ENV: test

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Rubocop
        run: bin/rubocop

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 1s
          --health-retries 10
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Prepare database
        run: bin/rake db:test:prepare
      - name: Run tests
        run: bin/rails test:all
